### ISSUE TITLE
CI failure: Badges are not being updated

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaCI/NanosoldierReports#27]
It has been more than a week since the github pages workflow started to show IO errors. Can someone look into that so that the badges can be updated again? Thanks!

**Comment by maleadt** [comment]
This is caused by the repository having grown too large, and is unlikely to get fixed anytime soon.
In the mean time, you can use the badge from JuliaHub: see e.g. https://juliahub.com/ui/Packages/LLVM/e8NBy/4.7.1. These badges are generated from the JSON database committed in this repo, which still works.

**Comment by maleadt** [comment]
Fixed!
